<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageVersion Include="CommunityToolkit.WinUI.Converters" Version="8.2.251219" />
    <PackageVersion Include="Google.Protobuf" Version="3.36.0" />
    <PackageVersion Include="Grpc" Version="2.46.6" />
    <PackageVersion Include="Grpc.Core" Version="2.46.6" />
    <PackageVersion Include="Grpc.Reflection" Version="2.83.0" />
    <PackageVersion Include="Grpc.Tools" Version="2.83.0" />
    <PackageVersion Include="MaterialDesignThemes" Version="5.3.2" />
    <PackageVersion Include="Microsoft.Extensions.DependencyInjection" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="10.0.11" />
    <PackageVersion Include="Serilog.Extensions.Logging" Version="10.0.0" />
    <PackageVersion Include="Serilog.Sinks.Console" Version="6.1.1" />
    <PackageVersion Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageVersion Include="ValueConverters" Version="3.1.22" />
  </ItemGroup>
</Project>