add_executable(sc-api-example-overview overview.cpp)
target_link_libraries(sc-api-example-overview PRIVATE sc-api)

add_executable(sc-api-example-effect_pipelines effect_pipelines.cpp)
target_link_libraries(sc-api-example-effect_pipelines PRIVATE sc-api)

add_executable(sc-api-example-game_loop game_loop.cpp)
target_link_libraries(sc-api-example-game_loop PRIVATE sc-api)

add_executable(sc-api-example-variable_definitions variable_definitions.cpp)
target_link_libraries(sc-api-example-variable_definitions PRIVATE sc-api)

add_executable(sc-api-example-pedal_state pedal_state.cpp)
target_link_libraries(sc-api-example-pedal_state PRIVATE sc-api)


add_executable(sc-api-example-device_info device_info.cpp)
target_link_libraries(sc-api-example-device_info PRIVATE sc-api)

add_executable(sc-api-led_control led_control.cpp)
target_link_libraries(sc-api-led_control PRIVATE sc-api)


add_library(sc-api-effects SHARED
	effects.cpp
	effects.h)
target_link_libraries(sc-api-effects PRIVATE sc-api)

add_executable(sc-api-effects-test effects-test.cpp)
target_link_libraries(sc-api-effects-test PRIVATE "C:/Users/olequ/Documents/Dev/DrivingLab/libs/sc-api/out/build/x64-Debug/examples/sc-api-effects.lib")