<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64;x86</Platforms>
    <AssemblyName>DrivingLab.$(MSBuildProjectName)</AssemblyName>
    <ApplicationIcon>Assets\Images\icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Content Include="appSettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" />
    <PackageReference Include="Grpc.Core" />
    <PackageReference Include="MaterialDesignThemes" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="System.IO.Ports" />
    <PackageReference Include="System.Management" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
    <ProjectReference Include="..\Tools\Tools.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Views\Driving.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Camera.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\TobiiEyeX.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Pointing.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Widgets\Joystick.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\StreamDeck.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\Screen.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\TensionR.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
    <Compile Update="Views\SoundPlayer.xaml.cs">
      <SubType>Code</SubType>
    </Compile>
  </ItemGroup>

</Project>
