syntax = "proto3";

package Common;

enum Status {
	Disconnected = 0;
	Connected = 1;
	Calibrating = 2;
	Calibrated = 3;
}

message Bool {
	bool value = 1;
}

message Int {
	int32 value = 1;
}

message String {
	optional string value = 1;
}

message Point {
	double x = 1;
	double y = 2;
}

message Size {
	double width = 1;
	double height = 2;
}

message Vector {
	double x = 1;
	double y = 2;
	double z = 3;
}

message UploadRequest {
  oneof payload {
    FileMetadata metadata = 1;
    bytes chunk = 2;
  }
}

message FileMetadata {
  string fileName = 1;
  string contentType = 2;
}

message UploadResult {
  string fileName = 1;
  int64 size = 2;
}
