syntax = "proto3";

package Driving;

import "protos/common.proto";
import "google/protobuf/empty.proto";

service Dispatcher {
	rpc IsAvailable (google.protobuf.Empty) returns (Common.Bool) {}

	rpc GetConnectionStatus (google.protobuf.Empty) returns (ConnectionStatus) {}
	rpc PlayPedalEffect (PedalEffect) returns (google.protobuf.Empty) {}
	rpc StopPedalEffect (StopEffect) returns (google.protobuf.Empty) {}

	rpc SetLogFileName (Common.String) returns (Common.Bool) {}

	// Initializes data reading stream, but the data is not polling to clients
	// until Start is called
	rpc ReadData (google.protobuf.Empty) returns (stream Data) {}
	rpc ReadEvents (google.protobuf.Empty) returns (stream Event) {}

	// Enable of disable data polling to clients
	// (has no effect if ReadData was not called yet)
	rpc Start (google.protobuf.Empty) returns (google.protobuf.Empty) {}
	rpc Stop (google.protobuf.Empty) returns (google.protobuf.Empty) {}
}

enum ActivePedal {
    None = 0x0;
    Brake = 0x1;
    Throttle = 0x2;
    Both = 0x3;
}

enum EffectType
{
    Constant = 0;
    Periodic = 1;
}

enum EffectVariable
{
    TorqueNm = 0;
    TorqueRelative = 1;
    ForceN = 2;
    ForceRelative = 3;
    PositionMm = 4;
}

message PedalEffect {
	ActivePedal pedal = 1;
	EffectType type = 2;
	EffectVariable variable = 3;
	float amplitude = 4;
	int32 duration = 5;
}

message StopEffect {
	ActivePedal pedal = 1;
}

message Button {
	bool isPressed = 1;
}

message RotaryButton {
	bool isPressed = 1;
	double rotation = 2;
}

message RotaryTiltButton {
	bool isPressed = 1;
	bool isTilted = 2;
	double rotation = 3;
	double degrees = 4;
}

message Data {
	double wheelRotation = 1;
	double throttlePedal = 2;
	double brakePedal = 3;
	double activeThrottlePedal = 4;
	double activeBrakePedal = 5;
	Button topLeftButton1 = 6;
	Button topLeftButton2 = 7;
	Button topLeftButton3 = 8;
	Button topRightButton1 = 9;
	Button topRightButton2 = 10;
	Button topRightButton3 = 11;
	Button bottomLeftButton1 = 12;
	Button bottomLeftButton2 = 13;
	Button bottomRightButton1 = 14;
	Button bottomRightButton2 = 15;
	Button leftPaddleShifter = 16;
	Button rightPaddleShifter = 17;
	RotaryButton rotaryButton = 18;
	RotaryTiltButton rotaryTiltButton = 19;
}

message ConnectionStatus {
	bool isBaseConnected = 1;
	bool isWheelConnected = 2;
	bool arePedalsConnected = 3;
	bool isActivePedalsHubConnected = 4;
	ActivePedal activePedalsConnected = 5;
}

message Event {
	oneof value {
		ConnectionStatus connectionStatus = 1;
		google.protobuf.Empty effectFinished = 2;
	}
}