syntax = "proto3";

package Gaze;

import "protos/common.proto";
import "google/protobuf/empty.proto";

service Dispatcher {
	rpc IsAvailable (google.protobuf.Empty) returns (Common.Bool) {}

	rpc SetLogFilename (Common.String) returns (Common.Bool) {}

	// Initializes data reading stream, but the data is not polling to clients
	// until Start is called
	rpc ReadData (google.protobuf.Empty) returns (stream Sample) {}

	// Enable of disable data polling to clients
	// (has no effect if ReadData was not called yet)
	rpc Start (google.protobuf.Empty) returns (google.protobuf.Empty) {}
	rpc Stop (google.protobuf.Empty) returns (google.protobuf.Empty) {}
}

// Gaze sample
message Sample {
	double timestamp = 1;
	double eyeX = 2;
	double eyeY = 3;
	double eyeXL = 4;
	double eyeYL = 5;
	double eyeXR = 6;
	double eyeYR = 7;
	double camXL = 8;
	double camYL = 9;
	double camXR = 10;
	double camYR = 11;
	enum Eye
	{
		None = 0;
		Left = 1;
		Right = 2;
		Both = 3;
	}
	Eye validEye = 12;
}

/*message Event {
	enum ID {
		Unknown = 0;		// args = []
		Calibrated = 1;		// args = []
	}

	ID id = 1;

	// General info, if any: check ID enum 
	repeated string args = 2;
}*/