syntax = "proto3";

package LeapMotion;

import "protos/common.proto";
import "google/protobuf/empty.proto";

service Dispatcher {
	rpc IsAvailable (google.protobuf.Empty) returns (Common.Bool) {}
	rpc IsConnected (google.protobuf.Empty) returns (Common.Bool) {}

	rpc Configure (Configuration) returns (google.protobuf.Empty) {}

	// Enable of disable sample streaming to clients
	rpc Start (google.protobuf.Empty) returns (google.protobuf.Empty) {}
	rpc Stop (google.protobuf.Empty) returns (google.protobuf.Empty) {}

	rpc ReadData (google.protobuf.Empty) returns (stream Sample) {}

	rpc ReadEvents (google.protobuf.Empty) returns (stream Event) {}
}

enum ConfigType {
	Default = 0;
	Ultrahaptics = 1;
	Custom = 2;
}

message Configuration {
	ConfigType config = 1;
	optional Common.Vector proximityBoxCorner1 = 2;
	optional Common.Vector proximityBoxCorner2 = 3;
	optional Common.Vector translation = 4;
	optional Common.Vector scale = 5;
}

message Sample {
	Common.Vector palm = 1;
	repeated Common.Vector fingertip = 2;
}

message Event {
	string name = 1;
	bool value = 2;
}