<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <UseWPF>true</UseWPF>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Logging" />
    <PackageReference Include="NAudio" />
    <PackageReference Include="NAudio.Wasapi" />
    <PackageReference Include="Serilog.Extensions.Logging" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="SharpDX.DirectInput" />
    <PackageReference Include="StreamDeckSharp" />
    <PackageReference Include="System.IO.Ports" />
    <PackageReference Include="System.Management" />
    <PackageReference Include="Tuni.SmartEyeTools" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Core\Core.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <PropertyGroup Condition="'$(PlatformTarget)' == 'x64'">
    <DefineConstants>$(DefineConstants);X64</DefineConstants>
  </PropertyGroup>

  <PropertyGroup Condition="'$(PlatformTarget)' == 'x86'">
    <DefineConstants>$(DefineConstants);X86</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="LeapCSharp.NET4.5, Version=3.2.1.0, Culture=neutral, processorArchitecture=MSIL">
      <SpecificVersion>False</SpecificVersion>
      <HintPath>..\libs\managed\LeapCSharp.NET4.5.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup Condition="'$(PlatformTarget)' == 'x86'">
    <Reference Include="Tobii.EyeX.Client.Net20">
      <HintPath>..\libs\x86\Tobii.EyeX.Client.Net20.dll</HintPath>
    </Reference>
    <Reference Include="Tobii.Gaze.Core.Net">
      <HintPath>..\libs\x86\Tobii.Gaze.Core.Net.dll</HintPath>
    </Reference>
    <Reference Include="EyeXFramework">
      <HintPath>..\libs\x86\EyeXFramework.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup Condition="'$(PlatformTarget)' == 'x64'">
    <Reference Include="Tobii.EyeX.Client.Net20">
      <HintPath>..\libs\x64\Tobii.EyeX.Client.Net20.dll</HintPath>
    </Reference>
    <Reference Include="Tobii.Gaze.Core.Net">
      <HintPath>..\libs\x64\Tobii.Gaze.Core.Net.dll</HintPath>
    </Reference>
    <Reference Include="EyeXFramework">
      <HintPath>..\libs\x64\EyeXFramework.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <None Visible="false" Include="..\libs\$(PlatformTarget)\LeapC.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Visible="false" Include="..\libs\$(PlatformTarget)\Tobii.EyeX.Client.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Visible="false" Include="..\libs\x86\TobiiGazeCore32.dll" Condition="'$(PlatformTarget)' == 'x86'">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Visible="false" Include="..\libs\x64\TobiiGazeCore64.dll" Condition="'$(PlatformTarget)' == 'x64'">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Visible="false" Include="..\libs\x86\myGazeAPI.dll" Condition="'$(PlatformTarget)' == 'x86'">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Visible="false" Include="..\libs\x64\myGazeAPI64.dll" Condition="'$(PlatformTarget)' == 'x64'">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Visible="false" Include="..\\libs\sc-api\out\build\$(PlatformTarget)-Debug\examples\sc-api-effects.dll">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <PropertyGroup>
    <Product>DrivingLab Server</Product>
    <PackageId>DrivingLabServer</PackageId>
    <Description>DrivingLab Server</Description>
  </PropertyGroup>

</Project>